"""empty message

Revision ID: 0af2e76d05d2
Revises: 534114296df7
Create Date: 2025-04-16 13:19:00.036925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel # edited



# revision identifiers, used by Alembic.
revision: str = '0af2e76d05d2'
down_revision: Union[str, None] = '534114296df7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('next_step_player_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'next_step_player_id')
    # ### end Alembic commands ###
