"""empty message

Revision ID: 1352fc989e05
Revises: 0af2e76d05d2
Create Date: 2025-04-16 16:58:27.113131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel # edited



# revision identifiers, used by Alembic.
revision: str = '1352fc989e05'
down_revision: Union[str, None] = '0af2e76d05d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('next_step_player_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('game', 'next_step_player_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('next_step_player_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('game', 'next_step_player_name')
    # ### end Alembic commands ###
