"""empty message

Revision ID: 534114296df7
Revises: 61ded8116156
Create Date: 2025-04-15 15:22:53.888811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel # edited



# revision identifiers, used by Alembic.
revision: str = '534114296df7'
down_revision: Union[str, None] = '61ded8116156'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('player1_id', sa.Integer(), nullable=True))
    op.add_column('game', sa.Column('player2_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'game', 'user', ['player1_id'], ['id'])
    op.create_foreign_key(None, 'game', 'user', ['player2_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_column('game', 'player2_id')
    op.drop_column('game', 'player1_id')
    # ### end Alembic commands ###
