"""empty message

Revision ID: 61ded8116156
Revises: 
Create Date: 2025-04-15 14:51:56.346741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel # edited



# revision identifiers, used by Alembic.
revision: str = '61ded8116156'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('result', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('player1_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('player2_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sid', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('sid')
    )
    op.create_table('user',
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gameboard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_sid', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_sid'], ['game.sid'], ),
    sa.ForeignKeyConstraint(['player_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ship',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_board_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_board_id'], ['gameboard.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ship')
    op.drop_table('gameboard')
    op.drop_table('user')
    op.drop_table('game')
    # ### end Alembic commands ###
