"""empty message

Revision ID: cbc6dfc7a76e
Revises: 1352fc989e05
Create Date: 2025-04-19 13:45:40.353169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel # edited



# revision identifiers, used by Alembic.
revision: str = 'cbc6dfc7a76e'
down_revision: Union[str, None] = '1352fc989e05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gameboard', sa.Column('checked_cells', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gameboard', 'checked_cells')
    # ### end Alembic commands ###
